controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Main arm controller (for MoveIt)
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Velocity controller for joystick Servo
    servo_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Gripper controller
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # TEST CONTROLLER (This was missing!)
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# Config for main arm
arm_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

servo_velocity_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5

# Config for gripper
gripper_controller:
  ros__parameters:
    joints:
      - Finger_Left_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Config for test controller
forward_position_controller:
  ros__parameters:
    joints:
      - Joint_1
    interface_name: position
